import { QrCode, FileImage, Minimize2, Maximize2, Crop, Binary, KeyRound, Hash, Braces, Regex, ShieldCheck, Palette, Type, Clock, Link as LinkIcon, FileText, Scan, Mic } from 'lucide-react';
import type { Tool } from './types';

export const toolsData: Tool[] = [
    {
        id: 'qr-generator',
        name: 'QR Code Generator',
        description: 'Create custom QR codes for URLs, text, and more.',
        icon: QrCode,
        path: '/tools/qr-generator',
        color: 'text-blue-400',
    },
    {
        id: 'image-converter',
        name: 'Image Converter',
        description: 'Convert images between PNG, JPG, and WEBP formats.',
        icon: FileImage,
        path: '/tools/image-converter',
        color: 'text-green-400',
    },
    {
        id: 'image-compressor',
        name: 'Image Compressor',
        description: 'Reduce image file size without losing quality.',
        icon: Minimize2,
        path: '/tools/image-compressor',
        color: 'text-purple-400',
    },
    {
        id: 'image-resize',
        name: 'Image Resize',
        description: 'Resize images to any dimension with presets.',
        icon: Maximize2,
        path: '/tools/image-resize',
        color: 'text-orange-400',
    },
    {
        id: 'image-crop',
        name: 'Image Crop',
        description: 'Crop images to perfect aspect ratios visually.',
        icon: Crop,
        path: '/tools/image-crop',
        color: 'text-pink-400',
    },
    {
        id: 'base64-image',
        name: 'Base64 ↔ Image',
        description: 'Convert images to Base64 or decode Base64 to images.',
        icon: Binary,
        path: '/tools/base64-image',
        color: 'text-cyan-400',
    },
    {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Generate secure passwords, API keys, and secrets.',
        icon: KeyRound,
        path: '/tools/password-generator',
        color: 'text-yellow-400',
    },
    {
        id: 'hash-encode',
        name: 'Hash & Encode',
        description: 'Generate MD5/SHA hashes and encode/decode text.',
        icon: Hash,
        path: '/tools/hash-encode',
        color: 'text-red-400',
    },
    {
        id: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Validate, prettify, and minify JSON data.',
        icon: Braces,
        path: '/tools/json-formatter',
        color: 'text-teal-400',
    },
    {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test and debug regular expressions in real-time.',
        icon: Regex,
        path: '/tools/regex-tester',
        color: 'text-indigo-400',
    },
    {
        id: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode JSON Web Tokens (Header & Payload).',
        icon: ShieldCheck,
        path: '/tools/jwt-decoder',
        color: 'text-rose-400',
    },
    {
        id: 'color-tools',
        name: 'Color / UI Dev',
        description: 'Color converter, palette generator, and contrast checker.',
        icon: Palette,
        path: '/tools/color-tools',
        color: 'text-fuchsia-400',
    },
    {
        id: 'case-converter',
        name: 'Text Case Converter',
        description: 'Convert text between snake, camel, pascal, and more.',
        icon: Type,
        path: '/tools/case-converter',
        color: 'text-lime-400',
    },
    {
        id: 'timestamp-converter',
        name: 'Unix Timestamp',
        description: 'Convert between Unix timestamps and human dates.',
        icon: Clock,
        path: '/tools/timestamp-converter',
        color: 'text-emerald-400',
    },
    {
        id: 'url-parser',
        name: 'URL Parser & Encoder',
        description: 'Parse, encode, and decode URLs and query params.',
        icon: LinkIcon,
        path: '/tools/url-parser',
        color: 'text-sky-400',
    },
    {
        id: 'markdown-previewer',
        name: 'Markdown Previewer',
        description: 'Write and preview Markdown content in real-time.',
        icon: FileText,
        path: '/tools/markdown-previewer',
        color: 'text-slate-400',
    },
    {
        id: 'face-detector',
        name: 'Face Detector',
        description: 'Detect faces in images using Chrome API.',
        icon: Scan,
        path: '/tools/face-detector',
        color: 'text-violet-400',
    },
    {
        id: 'voice-tools',
        name: 'Voice Tools',
        description: 'Speech recognition and text-to-speech converter.',
        icon: Mic,
        path: '/tools/voice-tools',
        color: 'text-amber-400',
    },
];
